import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pokémon Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full h-24 bg-yellow-400 dark:bg-yellow-600 flex items-center justify-center shadow">
          <h1 className="text-4xl font-extrabold text-gray-900 dark:text-gray-900 tracking-tight text-center w-full">
            Pokémon Search
          </h1>
        </header>
        {children}
      </body>
    </html>
  );
}
